#include "globalVar.h"

GtkWidget* window;
GtkWidget* timelabel;
GtkWidget* scorelabel;
GtkWidget* donelabel;
GtkWidget* spacelabel1;
GtkWidget* spacelabel2;
GtkWidget* spacelabel3;
GtkWidget* spacelabel4;
GtkWidget* spacelabel5;
GtkWidget* spacelabel6;
GtkWidget* spacelabel7;
GtkWidget* spacelabel8;
GtkWidget* vbox1;
GtkWidget* hbox1;
GtkWidget* hbox2;
GtkWidget* hbox3;
GtkWidget* hbox4;
GtkWidget* button1;
GtkWidget* button2;
GtkWidget* button3;
GtkWidget* button4;
GtkWidget* button5;
GtkWidget* button6;
GtkWidget* button7;
GtkWidget* button8;
GtkWidget* button9;
GtkWidget* button10;
GtkWidget* button11;
GtkWidget* button12;
GtkWidget* button13;
GtkWidget* button14;
GtkWidget* button15;
GtkWidget* button16;

const gchar* random_card[5][4][4];	
int Time = 60;		
char buf[100];		
char buf2[100];	
char buf3[100];	
char buf4[100];	
char buf5[100];	
int version=0;
const char* first;
const char* second;
int m=0;				
int s=0;				
int cnt = 0;				
int score = 0;			
int click = 0;		
int check[4][4] = {0,};	
int click_check[4][4] = {0,};
int start =0;		
int first_1, first_2, second_1, second_2;
int i=0;
