extern GtkWidget* window;
extern GtkWidget* timelabel;
extern GtkWidget* scorelabel;
extern GtkWidget* donelabel;
extern GtkWidget* spacelabel1;
extern GtkWidget* spacelabel2;
extern GtkWidget* spacelabel3;
extern GtkWidget* spacelabel4;
extern GtkWidget* spacelabel5;
extern GtkWidget* spacelabel6;
extern GtkWidget* spacelabel7;
extern GtkWidget* spacelabel8;
extern GtkWidget* vbox1;
extern GtkWidget* hbox1;
extern GtkWidget* hbox2;
extern GtkWidget* hbox3;
extern GtkWidget* hbox4;
extern GtkWidget* button1;
extern GtkWidget* button2;
extern GtkWidget* button3;
extern GtkWidget* button4;
extern GtkWidget* button5;
extern GtkWidget* button6;
extern GtkWidget* button7;
extern GtkWidget* button8;
extern GtkWidget* button9;
extern GtkWidget* button10;
extern GtkWidget* button11;
extern GtkWidget* button12;
extern GtkWidget* button13;
extern GtkWidget* button14;
extern GtkWidget* button15;
extern GtkWidget* button16;

extern const gchar* random_card[5][4][4];
extern int Time;		
extern char buf[100];	
extern char buf2[100];	
extern char buf3[100];	
extern char buf4[100];	
extern char buf5[100];	
extern int version;
extern const char* first;
extern const char* second;
extern int m;				
extern int s;				
extern int cnt;				
extern int score;			
extern int click;		
extern int check[4][4];	
extern int click_check[4][4];
extern int start;
extern int first_1, first_2, second_1, second_2;
extern int i;
